spring:
  datasource:
    url: jdbc:mysql://muneer-server01-file-sharing.k.aivencloud.com:21532/defaultdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
