spring:
  datasource:
    url: jdbc:mysql://muneer-server01-file-sharing.k.aivencloud.com:21532/defaultdb
    username: avnadmin
    password: AVNS_e4imt-YVjIzuPKbBq-2
  jpa:
    hibernate:
      ddl-auto: update
